import { PlannerAgent } from "../agents/planner";
import { CoderAgent } from "../agents/coder";
import { ReviewAgent } from "../agents/review";
import { GithubService } from "../git/github";

export class PipelineOrchestrator {
  private planner: PlannerAgent;
  private coder: CoderAgent;
  private reviewer: ReviewAgent;
  private github: GithubService;
  private readonly MAX_RETRIES = 3;

  constructor() {
    this.planner = new PlannerAgent();
    this.coder = new CoderAgent();
    this.reviewer = new ReviewAgent();
    this.github = new GithubService();
  }

  async execute(task: any) {
    const { repo, issueNumber, title } = task;
    let currentIteration = 0;
    let lastPatch = "";
    let lastReview: { status: "PASS" | "FAIL"; feedback: string } = { status: "FAIL", feedback: "" };

    console.log(`Starting production pipeline for ${repo} #${issueNumber}`);

    // 1. Plan
    const plan = await this.planner.generatePlan(task);
    console.log("Plan generated");

    // 2. Production Loop (Implement -> Review -> Fix)
    while (currentIteration < this.MAX_RETRIES) {
      console.log(`Iteration ${currentIteration + 1}/${this.MAX_RETRIES}`);
      
      // Implement or Fix
      if (currentIteration === 0) {
        lastPatch = await this.coder.generatePatch(plan, task);
      } else {
        console.log("Triggering auto-fix based on previous feedback...");
        lastPatch = await this.coder.generatePatch(
          `PLAN: ${plan}\n\nPREVIOUS FEEDBACK: ${lastReview.feedback}`,
          task
        );
      }

      // Review
      lastReview = await this.reviewer.reviewCode(lastPatch, plan);
      console.log(`Review status: ${lastReview.status}`);

      if (lastReview.status === "PASS") {
        console.log("Quality gate passed");
        break;
      }

      currentIteration++;
    }

    if (lastReview.status !== "PASS") {
      throw new Error(`Failed to produce a valid fix after ${this.MAX_RETRIES} attempts. Last feedback: ${lastReview.feedback}`);
    }

    // 3. GitHub Operations
    const branchName = `ai/fix-issue-${issueNumber}`;
    
    await this.github.createPullRequest({
      repo,
      branchName,
      title: `[AI-PROD] Fix for #${issueNumber}: ${title}`,
      body: `This PR was automatically generated by the AI Dev Production Pipeline.
      
      ## Implementation Plan
      ${plan}
      
      ## AI Review Feedback
      ${lastReview.feedback}
      
      ## Iterations
      Resolved in ${currentIteration + 1} iteration(s).`,
      patch: lastPatch
    });

    console.log(`Production-ready PR created for ${repo} #${issueNumber}`);
  }
}
